export const env = {
  NODE_ENV: 'development',
  DATABASE_DIALECT: '',
  DATABASE_HOST: '',
  DATABASE_PORT: 5566,
  DATABASE_USERNAME: '',
  DATABASE_PASSWORD: '',
  DATABASE_NAME: '',
  JWT_SECRET: 'jwt-secret',
  EMAIL_USER: 'email-user',
  EMAIL_PASS: 'email-pass',
  EMAIL_SERVICE: 'email-service',
  EMAIL_FROM: 'email-from',
  APPROVAL_EMAIL: 'approval-email',
  CLIENT_ORIGIN: 'https://localhost:3000',
  BACKEND_ORIGIN: 'https://localhost:1111',
  NODE_TLS_REJECT_UNAUTHORIZED: '0',
  COOKIE_DOMAIN: 'localhost',
  LOGGER_DATE_PATTERN: 'YYYY-MM-DD-HH',
  LOGGER_ZIP_ARCHIVE: true,
  LOGGER_MAX_SIZE: '10M',
  LOGGER_MAX_FILES: '7d',
  ADD_TO_SYNC_BACK_QUEUE: true,
  LOGGER_LEVEL: 'info',
  LOGGER_FILE_NAME: './boilerplate-%DATE%.log',
  PORT: 5050,
  HOST: '0.0.0.0',
  APPLICATION_NAME: 'app-name',
}

export const config = {
  port: 5500,
  host: '0.0.0.0',
  serviceName: 'test',
  portOut: 5500,
}